<html>
<head>
<title>Test</title>
$analytics()$
</head>
<body>
<form action="" method="post">
<p>
<label for="title">Title</label>
<input type="text" name="title">
</p>
<p>
<label for="author">Author</label>
<input type="text" name="author">
</p>
<p>
<label for="content">Content</label>
<textarea type="text" name="content" rows=40 cols=80></textarea>
</p>
<p>
<input type="submit" value="Send">
</p>
</form>
</body>
</html>