<html>
<head>
<title>Test Capabilities</title>
$analytics()$
</head>
<body>
<p>Capabilities</p>
<ul>
<li>BLOBSTORE: $blobstore.status$ - $blobstore.scheduledDate$</li>
<li>DATASTORE: $datastore.status$ - $datastore.scheduledDate$</li>
<li>DATASTORE_WRITE: $datastorewrite.status$
    - $datastorewrite.scheduledDate$</li>
<li>IMAGES: $images.status$ - $images.scheduledDate$</li>
<li>MAIL: $mail.status$ - $mail.scheduledDate$</li>
<li>MEMCACHE: $memcache.status$ - $memcache.scheduledDate$</li>
<li>TASKQUEUE: $taskqueue.status$ - $taskqueue.scheduledDate$</li>
<li>URL_FETCH: $urlfetch.status$ - $urlfetch.scheduledDate$</li>
<li>XMPP: $xmpp.status$ - $xmpp.scheduledDate$</li>
</ul>
</body>
</html>